### ISSUE TITLE
STN  example not working

### ISSUE THREAD

**Issue by sumeetssaurav** [oarriaga/spatial_transformer_networks#19]
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    model = STN()
  File "/home/vision/STN/STN.py", line 29, in STN
    x = Conv2D(32, (3, 3), padding='same')(interpolated_image)
  File "/home/vision/.virtualenvs/dl4cv/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 812, in __call__
    self.name)
  File "/home/vision/.virtualenvs/dl4cv/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/input_spec.py", line 155, in assert_input_compatibility
    ' input tensors. Inputs received: ' + str(inputs))
ValueError: Layer conv2d_2 expects 1 inputs, but it received 4 input tensors. Inputs received: [<tf.Tensor 'bilinear_interpolation/Placeholder:0' shape=<unknown> dtype=float32>, <tf.Tensor 'bilinear_interpolation/Placeholder_1:0' shape=(30,) dtype=float32>, <tf.Tensor 'bilinear_interpolation/Placeholder_2:0' shape=(30,) dtype=float32>, <tf.Tensor 'bilinear_interpolation/Placeholder_3:0' shape=(1,) dtype=float32>]

**Comment by JakobPCoder** [comment]
Same problem :/ cant find the problem

**Comment by zjhJOJO** [comment]
same problem.
